### ISSUE TITLE
WebSocket bomber demo

### ISSUE THREAD

**Issue by LinuxUserGD** [Faless/bomber-rtc#1]
Both WebSocket and WebRTC is implemented in Godot.

Is WebRTC the better standard for a high-level networked multiplayer with webassembly or is it possible to support both?

Are you planning to make a bomber-socket demo (bomber-rtc is already in this repository)?

Edit: Should I move this to the Godot Issues (as a Godot feature request / discussion)?
(ping @Faless )

**Comment by Faless** [comment]
As explained in the WebRTC reports:
https://godotengine.org/article/godot-webrtc-report1
https://godotengine.org/article/godot-webrtc-report2
https://godotengine.org/article/godot-webrtc-report3

WebSocket is not well suited for real-time applications. There is a multiplayer demo using websocket here:
https://github.com/LudiDorici/godot-websocket
which will likely be included in the officials godot demos.
